# Generated by Django 4.1 on 2022-08-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='emial',
            new_name='email',
        ),
    ]
